always fail, act on fail

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,6 +26,11 @@ jobs:
           - os: windows-latest
             python-version: "3.7"
     steps:
+      - name: Test fail
+        id: xfail
+        run: |
+          echo "deliberate fail"
+          exit 1
       - uses: actions/checkout@v2
       - name: Set up Python using Miniconda
         uses: conda-incubator/setup-miniconda@v2
@@ -44,7 +49,8 @@ jobs:
           pip install torch-geometric==1.7.0 --ignore-installed certifi
           pip install -e .[dev]
         shell: bash -l {0}
-      - name: Run unit tests
+      - name: Run tests
+        id: run_tests
         run: |
           pytest --nbmake --cov=kale
         shell: bash -l {0}
@@ -54,3 +60,8 @@ jobs:
         shell: bash -l {0}
       - name: Report coverage
         uses: codecov/codecov-action@v1
+      - name: Report failure
+        run: |
+          echo "Test run failed."
+        if: ${{ always() && steps.xfail.outcome == 'failure' }}
+        shell: bash -l {0}
